# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
	build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: rtl_tcp"
  org.opencontainers.image.description: "An add-on running rtl_tcp, allowing use of an rtl-sdr over the network or by other add-ons."
  org.opencontainers.image.source: "https://github.com/Oliver2213/ha-addons"
  org.opencontainers.image.licenses: "GNU General Public License 3.0"
args:
  TEMPIO_VERSION: "2021.09.0"
