# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: rtl_tcp
version: "0.0.1"
slug: example
description: An add-on running rtl_tcp, allowing use of an attached rtl-sdr over the network or by other add-ons.
url: "https://github.com/Oliver2213/ha-addons/tree/main/rtl_tcp"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  # vars...
schema:
  # schema...
# immage...
