# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: metermon
version: "0.2.0"
slug: metermon
stage: experimental
description: Metermon, a python script which connects to rtl_tcp and outputs various meter measurements to mqtt
url: "https://github.com/Oliver2213/ha-addons/tree/main/metermon"
startup: application
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  rtl_address: "127.0.0.1:1234"
  mqtt_address: "127.0.0.1"
  mqtt_port: "1883"
  mqtt_username: null
  mqtt_password: null
  send_by_id: true
  send_raw: false
schema:
  rtl_address: str?
  mqtt_address: str?
  mqtt_port: str?
  mqtt_username: str
  mqtt_password: str
  send_by_id: bool?
  send_raw: bool?

